name: Github Actions Zappy
on:
  push:
    branches-ignore:
      - "ga-ignore-*"
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  build_cross_platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Install Dependencies on Windows
      if: runner.os == 'Windows'
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

  check_compilation:
    needs:
      - build_cross_platform
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    container:
      image: epitechcontent/epitest-docker:latest
      options: --privileged
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        chmod +x start_project.sh
        ./start_project.sh
      timeout-minutes: 1

  push_to_mirror:
    needs:
      - check_compilation
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ secrets.REPOSITORY_SSH }}
        ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
