name: Github Actions R-Type
on:
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  build_cross_platform:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies on Linux
      if: runner.os == 'Linux'
      run: sudo apt-get update && sudo apt-get install -y build-essential
    - name: Install Dependencies on Windows
      if: runner.os == 'Windows'
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'

  check_compilation:
    needs:
      - build_cross_platform
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    # Linux os
    - name: Set up for Linux
      if: runner.os == 'Linux'
      run: |
        chmod +x start_project.sh
        ./start_project.sh
      timeout-minutes: 1
    # Windows os
    - name: Set up for Windows
      if: runner.os == 'Windows'
      run: |
        git config --global core.autocrlf false
        chmod +x start_project.sh
        ./start_project.sh
      timeout-minutes: 1

  push_to_mirror:
    needs:
      - check_compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror repository for Linux
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.REPOSITORY_SSH }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}