name: Github Actions Zappy

on:
  pull_request:
    branches-ignore:
      - "ga-ignore-*"

jobs:
  setup_dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install VCPKG and dependencies
      run: |
        git clone https://github.com/microsoft/vcpkg.git
        ./vcpkg/bootstrap-vcpkg.sh
        ./vcpkg/vcpkg install sfml boost libconfig

  build_project:
    needs: setup_dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Build the project
      run: |
        cmake -Bbuild -S. -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build
    - name: Check if executables exist
      run: |
        if [ ! -f build/my_project_executable ]; then
          echo "Executable not found!"
          exit 1
        fi
        if [ ! -f build/my_project_server_executable ]; then
          echo "Server executable not found!"
          exit 1
        fi

  push_to_mirror:
    needs: build_project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Mirror repository for Linux
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ secrets.REPOSITORY_SSH }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
